name: deploy
on: push

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            pkill -9 python
            sudo rm -rf flow_daily_bot
            sudo rm persistent_storage.pkl
            sudo git clone https://${{ secrets.TOKEN_GITHUB }}@github.com/udinilya/flow_daily_bot.git
#            python3 nohup flow_daily_bot/bot.py &
